<script>
  /**
  * new Promise((resolve, reject ))
  * 一个 Promise 有一下几种状态
  *  pending：初始状态，既不是成功，也不是失败
  *  fulfilled：操作成功完成
  *  rehected：操作失败
  *  重点
  *  pending 状态的 Promise 对象可能会变成 fulfilled 状态并传递一个值给相应的状态处理方法,
  *  也可能变为失败状态 （rejected）并传递失败信息。。。。。 后面还有很多，懒得写了 直接看文档吧
  *  https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise
  */

  // 用法
  // const promise = new Promise((resolve, reject) => {
  //   // 异步成功执行 resolve，否则执行 reject
  // }).then(res => {
  //   // resolve 触发第一个回调函数执行
  //   console.log('333')
  // }, (err) => {
  //   // reject 触发第二个回调函数执行
  // }).then(res => {
  //   // 需要保证 then 方法返回的依然是 promise
  //   // 这样才能实现链式调用
  // }).catch(reason => {

  // })
  // // 等待所有的 promise 都成功就会执行 then
  // // 反之只要有一个失败就会执行 catch
  // Promise.all([promise]).then((res) => {
  //   console.log(res, '0000')
  // }).catch((err) => {
  //   console.log(err, '我失败了')
  // })

  /*
  * 初步实现 Promise
  * 1、实现三种状态
  * 2、实现 then 方法两种回调函数的处理
  */

  // class ZPromise {
  //   // 传一个异步函数进来
  //   constructor (excutorCallBack) {
  //     // 初始化状态
  //     this.status = 'pending'
  //     // 返回值
  //     this.value = undefined
  //     // 存储所有成功状态
  //     this.fufillAry = []
  //     // 存储所有失败状态
  //     this.rejectedAry = []
  //     // 执行 Excutor
  //     let resolveFn = result => {
  //       // 如果不是初始化状态，就代表已经有结果了
  //       if (this.status !== 'pending') return
  //       let timer = setTimeout(() => {
  //         this.status = 'fulfilled'
  //         this.value = result
  //         // 执行每一个成功状态的回调
  //         this.fufillAry.forEach(item => item(this.value))
  //       }, 0)
  //     }
  //     let rejectFn = reason => {
  //       // 如果不是初始化状态，就代表已经有结果了
  //       if (this.status !== 'pending') return
  //       let timer = setTimeout(() => {
  //         this.status = 'rejected'
  //         this.value = reason
  //         // 执行每一个失败状态的回调
  //         this.rejectedAry.forEach(item => item(this.value))
  //       }, 0)
  //     }
  //     try {
  //       // 执行这个异步函数
  //       excutorCallBack(resolveFn, rejectFn)
  //     } catch (err) {
  //       // 有异常信息按照 rejected 状态处理，并且抛出异常
  //       rejectFn(err)
  //     }
  //   }
  //   then (fulfilledCallBack, rejectedCallBack) {
  //     // resolve 和 reject 函数做为一个微任务
  //     // 因此他们不是立即执行，而是等  then 调用完成后执行
  //     this.fufillAry.push(fulfilledCallBack)
  //     this.rejectedAry.push(rejectedCallBack)
  //     // push 过后他们被执行
  //   }
  // }

  // let p1 = new ZPromise((resolve, reject) => {
  //   setTimeout(() => {
  //     Math.random() < 0.5 ? resolve(100) : reject(-100)
  //   })
  // }).then(res => {
  //   console.log(res, '成功')
  // }, err => {
  //   console.log(err, '执行失败')
  // })

  /*
  * 完成链式调用
  * 最大的难点在于链式调用的实现，具体来说就是 then 方法的实现
  * 
  */
  class ZPromise {
    // 传一个异步函数进来
    constructor (excutorCallBack) {
      // 初始化状态
      this.status = 'pending'
      // 返回值
      this.value = undefined
      // 存储所有成功状态
      this.fufillAry = []
      // 存储所有失败状态
      this.rejectedAry = []
      // 执行 Excutor
      let resolveFn = result => {
        // 如果不是初始化状态，就代表已经有结果了
        if (this.status !== 'pending') return
        let timer = setTimeout(() => {
          this.status = 'fulfilled'
          this.value = result
          // 执行每一个成功状态的回调
          this.fufillAry.forEach(item => item(this.value))
        }, 0)
      }
      let rejectFn = reason => {
        // 如果不是初始化状态，就代表已经有结果了
        if (this.status !== 'pending') return
        let timer = setTimeout(() => {
          this.status = 'rejected'
          this.value = reason
          // 执行每一个失败状态的回调
          this.rejectedAry.forEach(item => item(this.value))
        }, 0)
      }
      try {
        // 执行这个异步函数
        excutorCallBack(resolveFn, rejectFn)
      } catch (err) {
        // 有异常信息按照 rejected 状态处理，并且抛出异常
        rejectFn(err)
      }
    }
    /*
    * 传参还跟之前一样
    */
    then (fulfilledCallBack, rejectedCallBack) {
      // 保证两者为函数
      typeof fulfilledCallBack !== 'function'
      ? fulfilledCallBack = result => result
      : null
      typeof rejectedCallBack !== 'function'
      ? rejectedCallBack = reason => {
        throw new Error(reason instanceof Error ? reason.message : reason)
      } : null
      // 返回新的 Promise 对象, 后面称呼它为 "新 Promise"
      return new ZPromise((resolve, reject) => {
        // 注意现在这个 this 指向目前的 Promise 对象，而不是新的 Promise
        // 很重要！！ 重点
        // 目前的 Promise (不是 return 的新的 Promise) 的 resolve 和 reject 函数其实一个作为微任务
        // 因此他们不是立即执行，而是等 then 调用完成后执行
        this.fufillAry.push(() => {
          try {
            // 把 then 里面的方法拿过来执行
            // 执行的目的已经达到
            let x = fulfilledCallBack(this.value)
            // 下面执行之后的下一步，也就是记录执行的状态，决定新 Promise 如何表变
            // 如果返回值 x 是一个 Promise 对象，就执行 then 操作 （注意，这里是重点）
            // 如果不是 Promise，直接调用新 Promise 的 resolve 和 reject 函数
            // 新 Promise 的 fulfillAry 现在为空，在新 Promise 的 then 操作后，新 Promise 的 resolve 执行
            x instanceof Promise ? x.then(resolve, reject) : resolve(x)
          } catch (err) {
            reject(err)
          }
        })
        this.rejectedAry.push(() => {
          try {
            // 把 then 里面的方法拿过来执行
            // 执行的目的已经达到
            let x = rejectedCallBack(this.value)
            // 下面执行之后的下一步，也就是记录执行的状态，决定新 Promise 如何表变
            // 如果返回值 x 是一个 Promise 对象，就执行 then 操作 （注意，这里是重点）
            // 如果不是 Promise，直接调用新 Promise 的 resolve 和 reject 函数
            // 新 Promise 的 fulfillAry 现在为空，在新 Promise 的 then 操作后，新 Promise 的 resolve 执行
            x instanceof Promise ? x.then(resolve, reject) : resolve(x)
          } catch (err) {
            reject(err)
          }
        })
      })
    }
    // catch 方法就是调用的 then 方法，走的报错逻辑而已
    catch (rejectedCallBack) {
      return this.then(null, rejectedCallBack)
    }
    // 为类的静态方法，而不在原型上
    // static 代表该方法为静态方法，无法在 原型上获取
    // all 方法返回一个新的 promise 对象，传入进去所有的 promise
    // 成功，才返回成功所有 promise 的返回值，有一个失败就返回失败
    static all (promiseAry = []) {
      let index = 0,
      result = []
      // 返回的是一个 Promise 对象
      return new ZPromise((resolve, reject) => {
        // 循环传递进来的 PromiseAry 集合
        for (let i = 0; i < promiseAry.length; i++) {
          promiseAry[i].then(val => {
            index++
            // 存储每一个 promise 返回的结果
            result[i] = val
            // 全部执行完毕之后执行当前 promise 成功方法
            if (index === promiseAry.length) {
              resolve(result)
            }
          }, reject)
        }
      })  
    }
    // ZPromise.race()
    // 当参数里的任意一个子 Promise 被成功或者失败后， 父 promise 的成功或者失败详情
    // 作为参数调用父 Promise 绑定的相应句柄，并返回该 Promise 对象
    // 
    /*
    * 原生里面是使用的迭代器，我在这里就没用了，只是达成了简单的效果
    * @parmas {Array} promiseAry 
    * @return Promise 返回一个 promise，一旦迭代器中的某个 promise 成功或失败。返回的promise 就会成功或者失败
    */
    static race (promiseAry) {
      return new ZPromise((resolve, reject) => {
        if (promiseAry.length === 0) return
        for (let i = 0; i < promiseAry.length; i++) {
          promiseAry[i].then(res => {
            return resolve(res)
          }, reject)
        }
      })
    }
    // 返回一个状态由 给定 value 决定的 Promise 对象。
    // 如果该值是 带有 then 方法的对象，返回的 Promise 对象的最终状态由 then 方法执行决定
    // 否则的话 返回一个 状态为成功的 Promise 对象，并且将 value 传递给 对应的 then 方法
    static resolve (value) {
      if (value instanceof Promise) return value
      return new ZPromise(resolve => resolve(value))
    }
  }

  // 测试用例
  // new ZPromise((res, rej) => {
  //   setTimeout(() => {
  //     Math.random() < 0.5 ? res('执行成功') : rej('执行的失败')
  //   }, 1000)
  // }).then(res => {
  //   console.log('到我这里了, 我是 then', res)
  //   return res + '第一个'
  // }).then(res => {
  //   console.log(res + '我是第二个 then', res)
  // }, rej => {
  //   console.log(rej, '我是报错信息')
  // })
  // new ZPromise((res, rej) => {
  //   rej('执行失败')
  // }).catch (err => {
  //   console.log(err)
  // })

  // Promise.all 的测试用例
  // let p1 = new ZPromise((res, rej) => {
  //   console.log('执行p1')
  //   return res('p1成功')
  // })
  // let p2 = new ZPromise((res, rej) => {
  //   console.log('执行p2')
  //   return res('p2成功')
  // })
  // let p3 = new ZPromise((res, rej) => {
  //   console.log('执行p3')
  //   return rej('p3失败')
  // })

  // ZPromise.all([p1, p2, p3]).then(res => {
  //   console.log(res)
  // }).catch(rej => {
  //   console.log(rej, '失败')
  // })

  // Promise.race() 的测试用例
  const p1 = new ZPromise((res, rej) => {
    setTimeout(() => {
      rej('one')
    }, 200)
  })

  const p2 = new ZPromise((res, rej) => {
    setTimeout(() => {
      rej('two')
    }, 100)
  })

  ZPromise.race([p1, p2]).then(val => {
    console.log(val, 'race')
  }).catch(err => {
    console.log(err)
  })
</script>